version: "3.5"

services:
  acme-register-seed:
    image: byrnedo/alpine-curl
    command: >-
      ${LEDGER_URL}/register
      -X POST
      -d '{"alias":"${ACME_LABEL}","seed":"${ACME_SEED}","role":"TRUST_ANCHOR"}'

  acme-aca-py:
    build:
      dockerfile: Dockerfile.acapy
      context: .
    depends_on:
      - acme-register-seed
      - acme-aca-py-tunnel-http
    ports:
      - "6002:6002"
      - "6000"
    entrypoint: /bin/bash -c 'export DOMAIN=$$(curl -s acme-aca-py-tunnel-http:4040/api/tunnels/command_line | grep -o "https:\/\/.*\.eu\.ngrok\.io") && aca-py start --endpoint "$$DOMAIN" "$$DOMAIN/http/ws" --admin 0.0.0.0 6002 --admin-insecure-mode --label "Workshop Acme Agent" --inbound-transport acapy_plugin_toolbox.http_ws 0.0.0.0 6000 --outbound-transport http --genesis-url ${LEDGER_URL}/genesis --wallet-type indy --wallet-name "Acme Wallet" --wallet-key AcmeWallet0000000 --seed ${ACME_SEED} --plugin acapy_plugin_toolbox --auto-accept-requests --auto-ping-connection --auto-respond-credential-proposal --auto-respond-credential-offer --auto-respond-credential-request --auto-store-credential --auto-respond-presentation-proposal --auto-respond-presentation-request --auto-verify-presentation --invite --invite-role admin --invite-label "${ACME_LABEL}" --debug-connections --debug-credentials --debug-presentations --enable-undelivered-queue --preserve-exchange-records'

  acme-aca-py-tunnel-http:
    image: wernight/ngrok
    ports:
      - "4040"
    environment:
      - NGROK_REGION=eu
      - NGROK_PORT=acme-aca-py:6000
      - NGROK_BINDTLS=true

  faber-register-seed:
    image: byrnedo/alpine-curl
    command: >-
      ${LEDGER_URL}/register
      -X POST
      -d '{"alias":"${FABER_LABEL}","seed":"${FABER_SEED}","role":"TRUST_ANCHOR"}'

  faber-aca-py:
    build:
      dockerfile: Dockerfile.acapy
      context: .
    depends_on:
      - faber-register-seed
      - faber-aca-py-tunnel-http
    ports:
      - "7002:7002"
      - "7000"
    entrypoint: /bin/bash -c 'export DOMAIN=$$(curl -s faber-aca-py-tunnel-http:4040/api/tunnels/command_line | grep -o "https:\/\/.*\.eu\.ngrok\.io") && aca-py start --endpoint "$$DOMAIN" "$$DOMAIN/http/ws" --admin 0.0.0.0 7002 --admin-insecure-mode --label "Workshop Faber Agent" --inbound-transport acapy_plugin_toolbox.http_ws 0.0.0.0 7000 --outbound-transport http --genesis-url ${LEDGER_URL}/genesis --wallet-type indy --wallet-name "Faber Wallet" --wallet-key FaberWallet0000000 --seed "${FABER_SEED}" --plugin acapy_plugin_toolbox --auto-accept-requests --auto-ping-connection --auto-respond-credential-proposal --auto-respond-credential-offer --auto-respond-credential-request --auto-store-credential --auto-respond-presentation-proposal --auto-respond-presentation-request --auto-verify-presentation --invite --invite-role admin --invite-label "${FABER_LABEL}" --debug-connections --debug-credentials --debug-presentations --enable-undelivered-queue --preserve-exchange-records'

  faber-aca-py-tunnel-http:
    image: wernight/ngrok
    ports:
      - "4040"
    environment:
      - NGROK_REGION=eu
      - NGROK_PORT=faber-aca-py:7000
      - NGROK_BINDTLS=true
