version: "3"
services:
  acme-register-seed:
    image: byrnedo/alpine-curl
    command: >-
      http://192.168.65.3:9000/register
      -X POST
      -d '{"alias":"Workshop Acme Agent","seed":"acme_seed_0000000000000000000001","role":"TRUST_ANCHOR"}'

  acme-aca-py:
    build:
      dockerfile: Dockerfile.acapy
      context: .
    depends_on:
      - acme-register-seed
      - acme-aca-py-tunnel-http
    ports:
      - "6002:6002"
      - "6000"
    entrypoint: /bin/bash -c 'export DOMAIN=$$(curl -s acme-aca-py-tunnel-http:4040/api/tunnels/command_line | grep -o "https:\/\/.*\.eu\.ngrok\.io") && aca-py start --endpoint "$$DOMAIN" --admin 0.0.0.0 6002 --admin-insecure-mode --label "Workshop Acme Agent" --inbound-transport acapy_plugin_toolbox.http_ws 0.0.0.0 6000 --outbound-transport http --genesis-url http://192.168.65.3:9000/genesis --wallet-type indy --wallet-name "Acme Wallet" --wallet-key AcmeWallet0000000 --seed acme_seed_0000000000000000000001 --plugin acapy_plugin_toolbox --auto-accept-requests --auto-ping-connection --auto-respond-credential-proposal --auto-respond-credential-offer --auto-respond-credential-request --auto-store-credential --auto-respond-presentation-proposal --auto-respond-presentation-request --auto-verify-presentation --invite --invite-role admin --invite-label "Acme Agent" --debug-connections --debug-credentials --debug-presentations --enable-undelivered-queue'

  acme-aca-py-tunnel-http:
    image: wernight/ngrok
    ports:
      - "4040"
    environment:
      - NGROK_REGION=eu
      - NGROK_PORT=acme-aca-py:6000
      - NGROK_BINDTLS=true

  faber-register-seed:
    image: byrnedo/alpine-curl
    command: >-
      http://192.168.65.3:9000/register
      -X POST
      -d '{"alias":"Workshop Faber Agent","seed":"faber_seed_000000000000000000001","role":"TRUST_ANCHOR"}'

  faber-aca-py:
    build:
      dockerfile: Dockerfile.acapy
      context: .
    depends_on:
      - faber-register-seed
      - faber-aca-py-tunnel-http
    ports:
      - "7002:7002"
      - "7000"
    entrypoint: /bin/bash -c 'export DOMAIN=$$(curl -s faber-aca-py-tunnel-http:4040/api/tunnels/command_line | grep -o "https:\/\/.*\.eu\.ngrok\.io") && aca-py start --endpoint "$$DOMAIN" --admin 0.0.0.0 7002 --admin-insecure-mode --label "Workshop Faber Agent" --inbound-transport acapy_plugin_toolbox.http_ws 0.0.0.0 7000 --outbound-transport http --genesis-url http://192.168.65.3:9000/genesis --wallet-type indy --wallet-name "Faber Wallet" --wallet-key FaberWallet0000000 --seed faber_seed_000000000000000000001 --plugin acapy_plugin_toolbox --auto-accept-requests --auto-ping-connection --auto-respond-credential-proposal --auto-respond-credential-offer --auto-respond-credential-request --auto-store-credential --auto-respond-presentation-proposal --auto-respond-presentation-request --auto-verify-presentation --invite --invite-role admin --invite-label "Faber Agent" --debug-connections --debug-credentials --debug-presentations --enable-undelivered-queue'

  faber-aca-py-tunnel-http:
    image: wernight/ngrok
    ports:
      - "4040"
    environment:
      - NGROK_REGION=eu
      - NGROK_PORT=faber-aca-py:7000
      - NGROK_BINDTLS=true
