version: "3.5"

services:
  acme-register-seed:
    image: byrnedo/alpine-curl
    command: >-
      ${LEDGER_URL}/register
      -X POST
      -d '{"alias":"${ACME_LABEL}","seed":"${ACME_SEED}","role":"TRUST_ANCHOR"}'

  acme-agent:
    build: .
    environment:
      NGROK_NAME: acme-ngrok
      AGENT_NAME: "${ACME_LABEL}"
      PORT: 3000
      ADMIN_PORT: 3001
      SEED: "${ACME_SEED}"
      LEDGER_URL: "${LEDGER_URL}"
    ports:
      - "3001:3001"

  acme-ngrok:
    image: wernight/ngrok
    command: ngrok http acme-agent:3000 --log stdout

  faber-register-seed:
    image: byrnedo/alpine-curl
    command: >-
      ${LEDGER_URL}/register
      -X POST
      -d '{"alias":"${FABER_LABEL}","seed":"${FABER_SEED}","role":"TRUST_ANCHOR"}'

  faber-agent:
    build: .
    depends_on:
      - faber-webhook-server
    environment:
      NGROK_NAME: faber-ngrok
      AGENT_NAME: "${FABER_LABEL}"
      PORT: 3000
      ADMIN_PORT: 3002
      SEED: "${FABER_SEED}"
      LEDGER_URL: "${LEDGER_URL}"
      WEBHOOK_URL: http://faber-webhook-server:1080
    ports:
      - "3002:3002"

  faber-webhook-server:
    image: ghcr.io/timoglastra/acapy-development-webhook-server
    ports:
      - 1080:1080

  faber-ngrok:
    image: wernight/ngrok
    command: ngrok http faber-agent:3000 --log stdout
